#############################################################################
# Makefile for building: dispvalues
# Generated by qmake (2.01a) (Qt 4.7.4) on: Mi. Apr 25 17:00:08 2012
# Project:  dispvalues.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-qvfb-4.7.4/bin/qmake -after  CONFIG+=debug -o Makefile dispvalues.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/qws/linux-x86-g++ -I. -I/usr/local/Trolltech/Qt-qvfb-4.7.4/include/QtCore -I/usr/local/Trolltech/Qt-qvfb-4.7.4/include/QtNetwork -I/usr/local/Trolltech/Qt-qvfb-4.7.4/include/QtGui -I/usr/local/Trolltech/Qt-qvfb-4.7.4/include -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/Qt-qvfb-4.7.4/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-qvfb-4.7.4/lib -lQtGui -L/usr/local/Trolltech/Qt-qvfb-4.7.4/lib -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-qvfb-4.7.4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/dispval.cpp \
		src/json/json.cpp \
		src/plotter/plotsettings.cpp \
		src/plotter/plotter.cpp \
		src/plotter/qpointd.cpp \
		src/spritevis/tacho.cpp \
		src/spritevis/zeiger.cpp \
		src/spritevis/qcustomgraphview.cpp moc_dispval.cpp \
		moc_plotter.cpp \
		moc_tacho.cpp \
		moc_qcustomgraphview.cpp \
		qrc_mice.cpp
OBJECTS       = main.o \
		dispval.o \
		json.o \
		plotsettings.o \
		plotter.o \
		qpointd.o \
		tacho.o \
		zeiger.o \
		qcustomgraphview.o \
		moc_dispval.o \
		moc_plotter.o \
		moc_tacho.o \
		moc_qcustomgraphview.o \
		qrc_mice.o
DIST          = /usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/common/qws.conf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/include_source_dir.prf \
		dispvalues.pro
QMAKE_TARGET  = dispvalues
DESTDIR       = 
TARGET        = dispvalues

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: dispvalues.pro  /usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/qws/linux-x86-g++/qmake.conf /usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/common/qws.conf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/lib/libQtNetwork.prl \
		/usr/local/Trolltech/Qt-qvfb-4.7.4/lib/libQtCore.prl
	$(QMAKE) -after  CONFIG+=debug -o Makefile dispvalues.pro
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/common/qws.conf:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-qvfb-4.7.4/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-qvfb-4.7.4/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-qvfb-4.7.4/lib/libQtNetwork.prl:
/usr/local/Trolltech/Qt-qvfb-4.7.4/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -after  CONFIG+=debug -o Makefile dispvalues.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/dispvalues1.0.0 || $(MKDIR) .tmp/dispvalues1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/dispvalues1.0.0/ && $(COPY_FILE) --parents src/dispval.h src/json/json.h src/plotter/plotsettings.h src/plotter/plotter.h src/plotter/converter.h src/plotter/qpointd.h src/spritevis/tacho.h src/spritevis/zeiger.h src/spritevis/qcustomgraphview.h .tmp/dispvalues1.0.0/ && $(COPY_FILE) --parents src/spritevis/mice.qrc .tmp/dispvalues1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/dispval.cpp src/json/json.cpp src/plotter/plotsettings.cpp src/plotter/plotter.cpp src/plotter/qpointd.cpp src/spritevis/tacho.cpp src/spritevis/zeiger.cpp src/spritevis/qcustomgraphview.cpp .tmp/dispvalues1.0.0/ && (cd `dirname .tmp/dispvalues1.0.0` && $(TAR) dispvalues1.0.0.tar dispvalues1.0.0 && $(COMPRESS) dispvalues1.0.0.tar) && $(MOVE) `dirname .tmp/dispvalues1.0.0`/dispvalues1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/dispvalues1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_dispval.cpp moc_plotter.cpp moc_tacho.cpp moc_qcustomgraphview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dispval.cpp moc_plotter.cpp moc_tacho.cpp moc_qcustomgraphview.cpp
moc_dispval.cpp: src/json/json.h \
		src/plotter/converter.h \
		src/plotter/plotter.h \
		src/plotter/plotsettings.h \
		src/plotter/qpointd.h \
		src/spritevis/tacho.h \
		src/spritevis/zeiger.h \
		src/dispval.h
	/usr/local/Trolltech/Qt-qvfb-4.7.4/bin/moc $(DEFINES) $(INCPATH) src/dispval.h -o moc_dispval.cpp

moc_plotter.cpp: src/plotter/plotsettings.h \
		src/plotter/converter.h \
		src/plotter/qpointd.h \
		src/plotter/plotter.h
	/usr/local/Trolltech/Qt-qvfb-4.7.4/bin/moc $(DEFINES) $(INCPATH) src/plotter/plotter.h -o moc_plotter.cpp

moc_tacho.cpp: src/spritevis/zeiger.h \
		src/spritevis/tacho.h
	/usr/local/Trolltech/Qt-qvfb-4.7.4/bin/moc $(DEFINES) $(INCPATH) src/spritevis/tacho.h -o moc_tacho.cpp

moc_qcustomgraphview.cpp: src/spritevis/qcustomgraphview.h
	/usr/local/Trolltech/Qt-qvfb-4.7.4/bin/moc $(DEFINES) $(INCPATH) src/spritevis/qcustomgraphview.h -o moc_qcustomgraphview.cpp

compiler_rcc_make_all: qrc_mice.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_mice.cpp
qrc_mice.cpp: src/spritevis/mice.qrc \
		src/spritevis/images/Blitz.png \
		src/spritevis/images/Blitzcol.png \
		src/spritevis/images/Funken.jpg \
		src/spritevis/images/windrad.jpg \
		src/spritevis/images/tachos.jpg \
		src/spritevis/images/cheese.png \
		src/spritevis/images/windradt.png
	/usr/local/Trolltech/Qt-qvfb-4.7.4/bin/rcc -name mice src/spritevis/mice.qrc -o qrc_mice.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: src/main.cpp src/dispval.h \
		src/json/json.h \
		src/plotter/converter.h \
		src/plotter/plotter.h \
		src/plotter/plotsettings.h \
		src/plotter/qpointd.h \
		src/spritevis/tacho.h \
		src/spritevis/zeiger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

dispval.o: src/dispval.cpp src/dispval.h \
		src/json/json.h \
		src/plotter/converter.h \
		src/plotter/plotter.h \
		src/plotter/plotsettings.h \
		src/plotter/qpointd.h \
		src/spritevis/tacho.h \
		src/spritevis/zeiger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dispval.o src/dispval.cpp

json.o: src/json/json.cpp src/json/json.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o json.o src/json/json.cpp

plotsettings.o: src/plotter/plotsettings.cpp src/plotter/plotsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plotsettings.o src/plotter/plotsettings.cpp

plotter.o: src/plotter/plotter.cpp src/plotter/plotter.h \
		src/plotter/plotsettings.h \
		src/plotter/converter.h \
		src/plotter/qpointd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plotter.o src/plotter/plotter.cpp

qpointd.o: src/plotter/qpointd.cpp src/plotter/qpointd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qpointd.o src/plotter/qpointd.cpp

tacho.o: src/spritevis/tacho.cpp src/spritevis/tacho.h \
		src/spritevis/zeiger.h \
		src/spritevis/qcustomgraphview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tacho.o src/spritevis/tacho.cpp

zeiger.o: src/spritevis/zeiger.cpp src/spritevis/zeiger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zeiger.o src/spritevis/zeiger.cpp

qcustomgraphview.o: src/spritevis/qcustomgraphview.cpp src/spritevis/qcustomgraphview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomgraphview.o src/spritevis/qcustomgraphview.cpp

moc_dispval.o: moc_dispval.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dispval.o moc_dispval.cpp

moc_plotter.o: moc_plotter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_plotter.o moc_plotter.cpp

moc_tacho.o: moc_tacho.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tacho.o moc_tacho.cpp

moc_qcustomgraphview.o: moc_qcustomgraphview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomgraphview.o moc_qcustomgraphview.cpp

qrc_mice.o: qrc_mice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_mice.o qrc_mice.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

